---
- hosts: all
  roles:
    - repos

- name: Install ElasticSearch
  hosts: elastic_hosts
  roles:
    - elasticsearch

- name: Install Fluentd
  hosts: fluent_hosts
  roles:
    - fluentd/server
    - fluentd/syslog
    - fluentd/elasticsearch

- name: Install Kibana
  hosts: kibana_hosts
  roles:
    - kibana

- name: Install Redis
  hosts: redis_hosts
  roles:
    - redis

- name: Install RabbitMQ
  hosts: rabbit_hosts
  roles:
    - rabbitmq/server

- name: Install Sensu
  hosts: sensu_hosts
  roles:
    - sensu/server

- name: Install Uchiwa
  hosts: uchiwa_hosts
  roles:
    - uchiwa

- name: Create firewall rules
  hosts: all
  roles:
    - firewall/commit
