---

# Set this to False if you do not want the playbooks to make changes
# to the system firewall.
firewall_manage_rules: true

# Force the use of ipv6
force_ipv6: false

# A lists of hashes containing data for configuration firewall rules
# to be created on each host groups
# .. code-block:: json
#
#     { host_group: [{port: PORT, source: SOURCE, protocol:PROTOCOL},
#                    {port: PORT, protocol:PROTOCOL}]}
firewall_data:
  rabbit_hosts:
    - port: "{{ rabbitmq_port }}"
      protocol: tcp
    - port: "{{ rabbitmq_ssl_port }}"
      protocol: tcp
  redis_hosts:
    - port: "{{ redis_listen_port }}"
      protocol: tcp
  sensu_hosts:
    - port: "{{ sensu_api_port }}"
      protocol: tcp
  uchiwa_hosts:
    - port: "{{ uchiwa_port }}"
      source: "{{ uchiwa_bind }}"
      protocol: tcp
    - port: "{{ opstools_apache_http_port }}"
      protocol: tcp
    - port: "{{ opstools_apache_https_port }}"
      protocol: tcp
  fluent_hosts:
    - port: "{{ fluentd_port|default(24224) }}"
      protocol: tcp
    - port: "{{ fluentd_port|default(24224) }}"
      protocol: udp
  elastic_hosts:
    - port: "{{ elasticsearch_port }}"
      protocol: tcp
  kibana_hosts:
    - port: "{{ kibana_server_port }}"
      source: "{{ kibana_server_bind }}"
      protocol: tcp
    - port: "{{ opstools_apache_http_port }}"
      protocol: tcp
    - port: "{{ opstools_apache_https_port }}"
      protocol: tcp
  grafana_hosts:
    - port: "{{ opstools_apache_http_port }}"
      protocol: tcp
    - port: "{{ opstools_apache_https_port }}"
      protocol: tcp
  graphite_hosts:
    - port: "{{ graphite_port }}"
      protocol: tcp
  collectd_hosts:
    - port: "{{ collectd_listen_port }}"
      protocol: tcp
  gnocchi_host:
    - port: "{{ gnocchi_port }}"
      protocol: tcp
