---
- name: Install chrony package
  package:
    name: '{{ chrony_package_name }}'
    state: present
  when: manage_packages|default(false)

- name: Generate chrony configuration
  template:
    src: chrony.conf.j2
    dest: '{{ chrony_config_file }}'
  notify: Restart chronyd

- name: Activate chrony service
  service:
    name: '{{ chrony_service_name }}'
    state: started
    enabled: true
  when: manage_services|default(false)
