---
- name: restart sensu server services
  service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - '{{ sensu_server_service_name }}'
    - '{{ sensu_api_service_name }}'
  when: manage_services|default(false)
