---
# Address on which Sensu should listen for connections.
sensu_api_bind: 0.0.0.0

# Address of the Redis server to which Sensu should connect.
sensu_redis_server: 127.0.0.1

# Port on which the Redis server listens.
sensu_redis_port: '{{ redis_listen_port }}'

# Password for authenticating to Redis.
sensu_redis_password: "{{ redis_password }}"

# A list of Sensu checks that will run on the overcloud hosts. The
# only required key for each item is `name`. The systemd `service`
# used in `systemctl` checks defaults to `openstack-<name>`, and the
# `subscribers` key defaults to `[ "overcloud-<name>" ]`.
#
# The following checks are disabled because the corresponding services
# are run as WSGI applications under Apache.  This means that we don't
# have a good client-side healthcheck until we make changes either to
# sensu packaging or our tripleo integration.
#
#     - name: ceilometer-api
#     - name: keystone-api
#       subscribers:
#         - overcloud-keystone
#         - overcloud-kestone
#     - name: aodh-api
#       subscribers:
#         - overcloud-ceilometer-aodh-api
#
sensu_overcloud_checks:
  - name: aodh-evaluator
    subscribers:
      - overcloud-ceilometer-aodh-evaluator
  - name: aodh-listener
    subscribers:
      - overcloud-ceilometer-aodh-listener
  - name: aodh-notifier
    subscribers:
      - overcloud-ceilometer-aodh-notifier
  - name: ceilometer-central
    subscribers:
      - overcloud-ceilometer-agent-central
  - name: ceilometer-collector
  - name: ceilometer-compute
  - name: ceilometer-compute
    subscribers:
      - overcloud-ceilometer-agent-compute
  - name: ceilometer-notification
    subscribers:
      - overcloud-ceilometer-agent-notification
  - name: ceilometer-polling
  - name: ceph-df
  - name: ceph-health
  - name: cinder-api
  - name: cinder-scheduler
  - name: cinder-volume
  - name: glance-api
  - name: glance-registry
  - name: haproxy
    service: haproxy
  - name: heat-api
  - name: heat-api-cfn
  - name: heat-api-cloudwatch
  - name: heat-engine
  - name: memcached
    service: memcached
  - name: neutron-api
    service: neutron-server
  - name: neutron-l3-agent
    service: neutron-l3-agent
  - name: neutron-metadata-agent
    service: neutron-metadata-agent
    subscribers:
      - overcloud-neutron-metadata
  - name: neutron-ovs-agent
    service: neutron-openvswitch-agent
  - name: nova-api
  - name: nova-compute
  - name: nova-conductor
  - name: nova-consoleauth
  - name: nova-libvirt
    service: libvirtd
  - name: nova-novncproxy
    subscribers:
      - overcloud-nova-vncproxy
  - name: nova-scheduler
  - name: pacemaker
    service: pacemaker
  - name: swift-proxy

# Username for openstack checks.
os_default_username: admin

# Password for openstack checks.
os_default_password: pass

# Project name (aka tenant) for openstack checks.
os_default_project: admin

# Authentication URL (Keystone server) for openstack checks.
os_default_auth_url: http://controller:5000/v2.0

# Region name for openstack checks.
os_default_region: regionOne

# Most common set of arguments user by remote API checks a.k.a. oschecks
os_auth_args: >-
  --os-username :::openstack.username|{{ os_default_username }}:::
  --os-password :::openstack.password|{{ os_default_password }}:::
  --os-tenant-name :::openstack.project_name|{{ os_default_project }}:::
  --os-auth-url :::openstack.auth_url|{{ os_default_auth_url }}:::

# A list of sensu checks that will run on an opstools server. List has the same
# format as sensu_overcloud_checks with the difference that subscribers
# defaults to the value of variable sensu_client_subscription
sensu_remote_checks:
  - name: cinder-api
  - name: glance-api
  - name: keystone-api
  - name: neutron-api
  - name: nova-api
  - name: cinder-volume
    args: >-
      --username :::openstack.username|{{ os_default_username }}:::
      --password :::openstack.password|{{ os_default_password }}:::
      --auth_url :::openstack.auth_url|{{ os_default_auth_url }}:::
      --tenant :::openstack.tenant_name|{{ os_default_project }}:::
    interval: 240
  - name: neutron_floating_ip
    interval: 240
  - name: nova_instance
    interval: 240
