---
sensu_api_bind: 0.0.0.0
sensu_api_port: 4567
sensu_api_server: localhost

sensu_redis_host: 127.0.0.1
sensu_redis_port: 6379

oscheck_default_username: admin
oscheck_default_password: pass
oscheck_default_project_name: admin
oscheck_default_auth_url: http://controller:5000/v2.0
oscheck_default_region_name: RegionOne
oscheck_default_subscribers: "\"overcloud-controller\""


oscheck_enable_amqp: true
oscheck_enable_ha: true
oscheck_enable_ceilometer: true
oscheck_enable_ceph: true
oscheck_enable_cinder: true
oscheck_enable_glance: true
oscheck_enable_neutron: true
oscheck_enable_nova: true
oscheck_enable_pacemaker: false
oscheck_enable_keystone: true

oscheck_subscribers_amqp: "{{ oscheck_default_subscribers }}"
oscheck_subscribers_ha: "{{ oscheck_default_subscribers }}"
oscheck_subscribers_ceilometer: "{{ oscheck_default_subscribers }}"
oscheck_subscribers_ceph: "{{ oscheck_default_subscribers }}"
oscheck_subscribers_cinder: "{{ oscheck_default_subscribers }}"
oscheck_subscribers_glance: "{{ oscheck_default_subscribers }}"
oscheck_subscribers_neutron: "{{ oscheck_default_subscribers }}"
oscheck_subscribers_nova: "{{ oscheck_default_subscribers }}"
oscheck_subscribers_pacemaker: "{{ oscheck_default_subscribers }}"
oscheck_subscribers_keystone: "{{ oscheck_default_subscribers }}"

oscheck_check_amqp_list:
  - sensu-client
  - sensu-server
  - sensu-api

oscheck_check_pacemaker_host_list:
  - openstack-cinder-volume
  - openstack-glance-api
